### ISSUE TITLE
Gov Team & things

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#103]
I'm updating our new web pages and under "[Advocacy](http://0.0.0.0:4000/open-austin-org/advocacy/)" we are putting the [current websites Policy section](https://www.open-austin.org/policy). 

I noticed this section says open austin "gov team". Is that a title we still want to use going forward or are there suggestions for anything else? 
<img width="666" alt="screen shot 2016-02-10 at 7 45 33 pm" src="https://cloud.githubusercontent.com/assets/10767430/12967707/0df6880a-d02f-11e5-80a7-288463db8906.png">

Also, thoughts about just putting the current policy section onto the advocacy page? Any wordsmithing recommended? 

I'm thinking of a better way to break this information up and what content needs to be added.

**Comment by mscarey** [comment]
I do feel better about "Policy Team" instead of "Gov Team." I almost want to avoid calling it a "team" because policy work is a function for everyone to help with when they want. But, there are situations where people might want to refer to themselves as policy team members in correspondence, so "Policy Team" is good.

**Comment by VictoriaODell** [comment]
Closing this. 

We are using "Policy Team" now  on the site. Going to open an issue about IA of advocacy page in the open-austin.github.io repo.
