### ISSUE TITLE
Update Projects we want highlighted for CoA "App Library"

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#153]
The CoA just [updated the Open Data Portal homepage](https://data.austintexas.gov/). One of the main tiles takes visitors to an ["App Library"](http://austintexas.gov/page/mobile-app-library) which includes "Austin Community Apps". We should decide what projects we want highlighted from there.
- [ ] Choose projects we wanted highlighted
- [ ] Send Update OA Logo
- [ ] Contact Ashlee Harris with City Public Info ashlee.harris@atxad.org

![](http://dsh.re/3e045)
![](http://dsh.re/dc459)

**Comment by mateoclarke** [comment]
@luqmaan, can you help me select a few of the projects we should highlight that use City Open Data for their App Library page? I don't think they necessarily need to be projects from our volunteers.

**Comment by mateoclarke** [comment]
@luqmaan @VictoriaODell What projects did we choose to highlight for the sponsorship packet. Should we use the same ones for this?

**Comment by amaliebarras** [comment]
hey what's the status on this mateo? I was going to create a new card for our Open Austin projects portfolio but then I saw this. can this be closed out or do you want us to select a few?

**Comment by mateoclarke** [comment]
We could still update what community apps we wanted to be highlighted via the City. If they use portal data, that would be good. Doesn't have to overlap with projects we want to highlight in our own portfolio but it make sense to think about it at the same time.

**Comment by hlupico** [comment]
I'll look through the projects to see which best fit the description that @mateoclarke mentioned and then circle back with you all to confirm the list to be submitted to the city.

**Comment by hlupico** [comment]
@mateoclarke @amaliebarras - Are we comfortable with having links to github repos listed on the App Ideas page? Currently the Bike Buddy and Campaign Contribution Directory project links bring users to the github repo. VoteATX isn't currently working - if we are up for linking 
users to repos than we can request that the link be updated to bring the user to the repo rather than the website.

Campaign Contribution Directory has a description for the Dangerous Dog app mentioned in the summary of the project...? Lol - I can suggest a copy update there.

**Comment by mateoclarke** [comment]
@hlupico, yeah I think we should ask the City's CPIO office to remove projects that are defunct like the ones you mentioned.

The goal of this would be to send them some better projects so they can update their site with projects that better reflect our current work.

**Comment by amaliebarras** [comment]
@hlupico do you think it'd be accurate to send them the ones in the most recent [project board](https://github.com/open-austin/project-ideas/projects/1) column? I'm kinda thinking as we start to settle into our roles & get more familiar with the active projects the high-activity projects will become clearer to us. I'm gonna drag this card to the backlog for now, just wanted to add ya to it since it's delivery lead stuff!

**Comment by hlupico** [comment]
@amaliebarras - If I'm looking in the correct place I see that some of those projects are live at the moment.

**Comment by mateoclarke** [comment]
Only the ones under "Austin Community Apps" are the ones related to Open Austin.

**Comment by werdnanoslen** [comment]
Should we list all of our featured projects? Would be cool if the Austin Community Apps could auto-post based on our site's RSS feed of new featured projects, too

**Comment by mateoclarke** [comment]
Would be cool, but I'm not sure the City would invest the time necessary (or cede control of content on their page) to sync to an external RSS feed. It also looks like that tile is not longer there on the Data Portal landing page.

Ashlee is great though. If you ever want to reach out to talk about it you should. Feel free to pull me if you think I could help bridge any gaps.

**Comment by werdnanoslen** [comment]
Yeah, could you introduce me? We can discuss how we might share OA's work on a city site, whether it's as a tile there or not. 

Since they removed that tile though, I'll just close this issue and open a new one depending on how the convo goes.

**Comment by mateoclarke** [comment]
✉️  💨
