### ISSUE TITLE
Update Civic Hacking 101

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#178]
We should make Civic Hacking 101 more about projects our members have made.

**Comment by mateoclarke** [comment]
yup

**Comment by amaliebarras** [comment]
https://docs.google.com/presentation/d/1tceKempW_8ZoxzeGcfuC1K96kBz0zaMkBxmT1pgv1bo/edit#slide=id.g18065a33fa_0_303

**Comment by werdnanoslen** [comment]
### Questions from 101 (Mar 28)
* Relationship between Austin and civic hackers: how often do projects come from the city or from the public not involved directly in OA?
* How to sync up with projects that don't have a present contributor at a meeting?
* Start out talking about CfA, then Open Austin?
* Flip it, talk about high level things first, then go into more technical aspects, or PM aspects, or advocacy aspects, etc?

**Comment by hlupico** [comment]
Another Idea:
- Link more examples of how people can contribute through other means than programming.

**Comment by VictoriaODell** [comment]
Just throwing this out there because it's something I though of before. 

It would be cool to have a general civic hacking 101 but also have a few additional slides that cover how different types of people can get more involved on different tasks. Like what @hlupico mentioned above. I think this would be helpful if we ever need to present to a specific crowd but and also just break down the different opportunities in the org.    

Ex:  for developers, data scientist, designers, marketers, policy people, etc. 

I think at the least having a blog post with that info would be helpful. 

Just getting our civic hacking 101, once it's updated, into a blog post and expanded upon would be good too content wise.

**Comment by hlupico** [comment]
Link for Civic Hacking 101 outline
https://docs.google.com/document/d/1Xvhe8ctjoBANpIVvFS6ah8Wl0fdtrm3_Itt5YfH7AE4/edit

**Comment by werdnanoslen** [comment]
:point_up: :fire:

**Comment by werdnanoslen** [comment]
let's also add a List of beginner friendly projects and tutorials (#202) and then publish it (#238) so that it's easily discoverable for people who can't get the in-person 101 but still would benefit from a comparable experience.

**Comment by werdnanoslen** [comment]
Merged all versions & changes of 101 into a single deck: https://docs.google.com/presentation/d/1YnjujQQ1XqbRIdsorfUfKaR-oE_hWy1itZrZAVQZ6vI/edit#slide=id.g18065a33fa_0_173

This presentation is on par with suggestions in Hannah's doc: https://docs.google.com/document/d/1Xvhe8ctjoBANpIVvFS6ah8Wl0fdtrm3_Itt5YfH7AE4/edit

And we can point to the project ideas repo milestones for which current projects they can get involved in. Since projects change so often (including whether their champions are active), it would be best for a leader to make the call on which ones are beginner friendly. Ask the projects lead (currently me) for more advice at any given time.

And with that, I'll close this issue. If there's anything specific that was missed, open a new issue :D
