### ISSUE TITLE
CRM to bring membership data together

### ISSUE THREAD

**Issue by amaliebarras** [open-austin/iced-coffee#18]
Approach: 
one firm/spreadsheet for tracking growth - and getting an idea for who people are, 
and one spreadsheet for tracking activity : in person, slack, otherwise. 
(we can always join that data w/ member data but I don’t know a good way to architect it so it all lives in one place)

possible existing tool to leverage: 
https://github.com/CfABrigadePhiladelphia/laddr

Possible data sources : 
Signup
  date
  Name
  Email
  Opt-In
  Feedback Field

Google Group
  Join date
  Name
  Email

Hack night signin
  Date
  Name
  Email
  Opt-In
  Free response (interests)
  Slack Opt-in

Meetup signin
  date
  Name
  Email
  Opt-In
  Slack opt-in

Meetup
  Name
  Date Joined
  Last Visited
  (Hopefully) email

Twitter 
  Need input - possible hack project? 
https://docs.google.com/spreadsheets/d/1oNLpIwEdIPrvU5VrT-ejHtIMzT1sk7jYV47U32XYMrg/edit#gid=1317192611

Facebook 
  Need input

Github
  Need input

Slack
  date
  Slack handle
  email
  Active status

**Comment by mateoclarke** [comment]
this was recommended as a good tool:
https://airtable.com/templates/sales-and-customers/personal-crm

**Comment by amaliebarras** [comment]
AirTables is pretty great, but in order to switch over to it we would have to switch forms (again). Not only would this be super confusing, but I played around with the forms feature, and it looks like there's no way to add a timestamp field, or multiple choice inputs. This would make all our responses open-text which would become harder to use. 

A workaround would be using the same google form and manually pasting data every week into AirTable. But then what we have is basically the same. The difference would be that the fields can link between spreadsheets.  I haven't tried doing this using macros in Google Sheets but I know it's possible in excel.

**Comment by mateoclarke** [comment]
@amaliebarras: Can you add the AirTable credentials to LP? I'd like to poke around. 

I thought one of the selling points with AirTables was how easily it integrates with other services.
https://airtable.com/integrations/googledrive. 

On the integration and automation note, https://zapier.com/ would be a good tool to try to automate things. I'd love for us to have this: https://zapier.com/zapbook/meetup/

I don't think switching the form is that big a deal. What I'm envisioning in the medium-term (once the website is live) are two urls with embedded forms. open-austin.org/checkin & open-austin.org/signup. We'd have embedded Google forms or just a plain form that submits data to some datastore (as simple as Google Drive or AirTables). One url would be for folks that just wanna claim their attendance, the other would be for brand new people.

**Comment by amaliebarras** [comment]
I added the credentials. 

I didn't know about the Google Drive integration, I must have missed that selling point. It wasn't super obvious how to connect, the way that I logged in, hope you have better luck when you poke around!

Those zapier connections look amazing! Pulling in the Meetup RSVPs would be an awesome place to start. That would make this solution make a lot more sense, if we can pull all the online data in. 

In theory switching the form doesn't have to be a big deal, but it can quickly turn into a mess when people are using old forms, and data gets lost, and we have to put it back together later. I guess as long as it's documented well it should be fine. I love the idea of embedding the signup form on the website, but I still don't think we need a form for checkin. A person manually tracking guarantees that we capture everyone there - and taking little notes creates a more human connection between us and the community. It's more reliable plus less work for members.

**Comment by mateoclarke** [comment]
We needed (and will continue to need) a checkin form at Civic Hack Saturday. Since people came and left at all different times, there was no set time for intros. There was no opportunity to do manual check-ins and add personal notes. Luqmaan didn't pause at any point for a standup either (That might be something to add in the future?). 

I think the manually note tracking is totally worth doing when we have an event where everyone introduces themselves. And it would be great to make sure the note taker is spelling a name correctly, or associating qualitative notes with an unique id like an email. But there are times when people arrive after intros. Right now we can't guarantee their attendance is counted. 

So not saying we should get ride of manual attendance because I agree it has a human connection value, but we should think of ways to have those notes and manually added records associate back to one "user".

**Comment by amaliebarras** [comment]
Okay, good points. I didn't think about the Saturday Civic Hack format being come and go as you please. I guess we should have both. 

I agree that having people sign-in would make the links back to the membership database smoother, because right now I have to manually check spellings for those who've filled it out, and I just try my best on the others. 

I just know that in the past when we've relied on people to sign-in, the attendance is under-reported, so that's why I'm being adamant about still manually counting. Example, at the 1/11 meetup where we made a big deal about signing in and had swag for the first time, we had 17 signup, but I counted 27 as attending. Even subtracting us 5 coreteam members, that's still 23% of attendees that wouldn't have been counted. It's not just a human connection value, it lets us be sure that we're tracking our growth accurately

**Comment by mateoclarke** [comment]
@amaliebarras, I would like to circle back to this. Maybe after our Leadership Summit we reevaluate the needs here?

**Comment by amaliebarras** [comment]
Assigning to membership team lead! Happy to meet and give more context to this but I'll leave it to @seandellis to push fwd!

**Comment by seandellis** [comment]
Thanks @amaliebarras. Let's set up a time to review next week.

**Comment by amaliebarras** [comment]
@seandellis a couple months into the role ... do you think we still need this? if so, do you need anything from me? if not, can I archive the issue? or should I backlog it?

**Comment by seandellis** [comment]
@amaliebarras To be honest, I haven't been manually tracking individual attendance. Is there a goal for doing so? Otherwise I don't think it's worth the time.

However, tracking the number of actual attendees is great because it lets us know how large our venues need to be as well as measure growth and dropoff.

I'd recommend we use the following process for future membership tracking:

## Standard Events

* Ask attendees to visit our [Sign In](https://open-austin.org/welcome) page. If an attendee, doesn't sign in then they aren't that interested. That's their loss.
 
* Count number of actual attendees at beginning of event. Give number to one of the Event Hosts.

* After the event, manually enter the attendance. (Requires Event Host access)

	* Visit event page
	* In the attendees column, select "Tools" -> "Edit Attendance"
	* Enter the number of attendees

* Within 48 hours, send out a Meetup message thanking attendees and asking them to Sign In if they forgot.

## Special Events (Events limited due to space or a Sponsor wanting a list of attendees)

* Have people check in at the door with an attendant as they get entered into the event's sign in form.

**Comment by amaliebarras** [comment]
The only thing we were really using it for was swag ... but it would also be the only way to really measure retention. 

I think the new process sounds just fine. From a projects perspective I'm less concerned about attendance tracking and more concerned about keeping track of interested attendees skills / interests, which I think this covers.
