### ISSUE TITLE
Aug 16 Meetup

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#189]
- [x] Confirm venue
- [x] Confirm speaker(s)
- [x] Agenda or [slides](https://docs.google.com/presentation/d/1_ZxJEOcp_P1PYRp-fbb82GPT6YiTbn90X5nUb8RAox4/edit#slide=id.g105efe3300_0_58)
- [x] Twitters/Facebooks, etc
- [x] Bring swag, projector, banner, table card stands

**Comment by VictoriaODell** [comment]
Is there a link to Jen and Itamar's presentation?

**Comment by mateoclarke** [comment]
i'll ask them...

**Comment by scascketta** [comment]
I found a [page](https://www.us-ignite.org/globalcityteams/actioncluster/tj9yFjegSYzDXpdrBbAKYZ/) that has an overview of topics similar to what they presented Monday evening. Closest thing I can find to a 1st-party source in lieu of their actual slides.

---

In the meantime, here's a recap of what I remember from their presentation and answers to questions from the crowd. Please comment if I have something wrong or if I missed something.

The city has installed sensors at intersections in Austin, focused around central Austin near downtown for use in traffic studies and real-time adaptive traffic control. Adaptive traffic control could involve modifying traffic signal timing based on real-time data from these sensors.

At the moment, there are Bluetooth, Wi-Fi, and radar sensors in place. For now, Itamar said that they've only looked at the data from the Bluetooth sensors in-depth. The Bluetooth sensors look for devices with active Bluetooth (which could be pedestrians, cyclists, cars with Bluetooth-enabled stereo) and log the time, the location of the sensor, and a hash of the device's MAC address. Using the hashed MAC address, you could track a device as it travels between sensors to get an idea of the travel time. According to Itamar, the documentation for the Bluetooth sensor is not public so they had to email the vendor to get a user manual. The data comes in two formats, CSV and XML. I asked him about the range of the sensor but he didn't know at the time.

The radar sensors have the potential to be more useful than the Bluetooth sensors because it could not only detect pedestrians, cyclists, and cars without active Bluetooth devices, but could also measure their speed.

In order to access the data from the Bluetooth sensors, Itamar said you have to access a machine on the city's VPN, but otherwise, it's not particularly difficult to access the data. Pending approval, he said that the data could become public within a few weeks though it could take as long as December 2016.

**Comment by VictoriaODell** [comment]
Sweet. I already started something but have been working on editing. We can roll this into the sensor sections? Note I'm still editing so it's probably wonky. 

# August Open Gov & Civic Tech Meetup Recap-Transportation & Sensors

---
layout: post
title: August Open Gov & Civic Tech Meetup Recap-Transportation & Sensors
date: 2016-08-16
type: post
published: true
thumb: August-meetup-thumb.jpg
thumbalt:  
author:
  first_name: Victoria
  last_name: O'Dell
  
---



### UT Center for Transportation Research 

For our August meeting we invited Jen Duthie([twitter](https://twitter.com/jenduthie?lang=en)) & Itamar Gal, from the [UT Center for Transportation Research](https://ctr.utexas.edu/). As part of the University of Texas, the Center for Transportation Research tries to work openly and in collaboration with the city and community. The CTR is apart of the UT college of engineering. Jen Duthie directs the research group for Network Modeling Center in UTCTR. It's called the networking modeling center because of the work they do around transportation network modeling and predicting routes.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Dr. <a href="https://twitter.com/jenduthie">@JenDuthie</a> &amp; Itamar Gal of <a href="https://twitter.com/CTRUTAustin">@CTRUTAustin</a> describe the <a href="https://twitter.com/hashtag/transportation?src=hash">#transportation</a> Data Rodeo concept to <a href="https://twitter.com/openaustin">@openaustin</a>  <a href="https://t.co/ZEdVgDsPFh">https://t.co/ZEdVgDsPFh</a></p>&mdash; Steven Polunsky (@StevenPolunsky) <a href="https://twitter.com/StevenPolunsky/status/765347403230621697">August 16, 2016</a></blockquote>



### Connecting the Data

Duthie pointed out that it's currently very slow and hard to connect all the data points. It's difficult to know who is collecting what data and what tools there are using to understand and share it. Duthie said " the gap [for collaboration] is so big and it doesn't really need to be there." She highlighed the need "to cut through the red tape" and make data more accessible.  

Because of this UTCTR are working on [Data Rodeo](datarodeo.org). Data Rodeo initially came out as a smart cities challenge. It focuses on the following: 

- Access to data & Tool
- Innovation & Collaboration
- Data centric research & Learning
- Enabling Smart Cities

Although the city didn't win the [Smart Cities grant](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0ahUKEwjL89Ht_8TOAhXCSiYKHbLPD5oQFggqMAI&url=http%3A%2F%2Fkxan.com%2F2016%2F06%2F21%2Faustin-loses-out-on-50-million-smart-city-bid%2F&usg=AFQjCNHgMQ8YuKtBg88KfBVLF2ss3_SFrw&sig2=0sBJUuKaffw9gUWfUmNrIA&bvm=bv.129759880,d.eWE), UTCTR continues the project to connect data to people.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">&quot;Getting access to data is slow but we are making huge strides&quot; - Jen Duthie from <a href="https://twitter.com/CTRUTAustin">@CTRUTAustin</a> <a href="https://t.co/2tsIEdkuzH">pic.twitter.com/2tsIEdkuzH</a></p>&mdash; Open Austin (@openaustin) <a href="https://twitter.com/openaustin/status/765348647114465280">August 16, 2016</a></blockquote>

### Sensors

Itmar Gal finished out the the presentation. He stated that although collecting transportation data and collaboration are great, they're not neccessarily a city priority right now. Though this is true, the city currently has sensors that are collecting data on the streets. He challenged the group to find uses for the data to help push interest and investment in the sensors and data. 

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Itamar shows a map where current static bluetooth sensors are located in the city. <a href="https://t.co/eYM3a9e3jf">pic.twitter.com/eYM3a9e3jf</a></p>&mdash; Open Austin (@openaustin) <a href="https://twitter.com/openaustin/status/765351053193728002">August 16, 2016</a></blockquote>


Itmar showed the group a map that shows all the bluetooth sensors that the city has. The current bluetooth sensors are field sensor devicse and sit statically at intersections or near them. The bluetooth devices have their own web servers that the city can connect to and monitor. 

After displaying the data, Itmar highlighed that it would be great to expand the network. Jen Pointed out the city is struggling between starting and maintianing the own network or paying for subscription of data from other entities.  


Itamar concluded with am animated heatmap of the bluetooth sensor reading throught the day with CardoDB. He believes the community could do interesting things with the data. Jen said that "we put out our reports and show our story but want to give other people the chance to let other stories emerge". 

To get involved, give feedback, or ask questions then you can email Jen Duthie, Ph.D., PE at jduthie@utexas.edu or Itamar Gal, Ph.D. at igal@utextas.edu

## Continue the Conversation

Join the Open Austin community on Slack: [Get an invite](http://slack.open-austin.org/)
<br>
RSVP for our future events on Meetup: [RSVP](http://www.meetup.com/Open-Austin/)
<br>
[Follow us on Twitter](https://twitter.com/openaustin?lang=en)
& [Like us on Facebook](https://www.facebook.com/Open-Austin-412390968837071/)

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
 
 
#### Rose, Bud, Thorn:

- Bud | Opportunity : At last UTC meeting city is collecting more data  
- Thorn | : Harris County data, tradeoffs of publishing 
- Rose | Project Success: Open Ausin site is now serving everything with https. Pandas had a issue resloved 


https://docs.google.com/presentation/d/1_ZxJEOcp_P1PYRp-fbb82GPT6YiTbn90X5nUb8RAox4/edit?usp=sharing

**Comment by scascketta** [comment]
Yeah I think the relevant parts from my comment to add to the Sensors section would be:

> The Bluetooth sensors look for devices with active Bluetooth (which could be pedestrians, cyclists, cars with Bluetooth-enabled stereo). When an active Bluetooth device is nearby, the sensor logs the time, the location of the sensor, and a hash of the device's MAC address. Using the hashed MAC address, you could track a device as it travels between sensors to get an idea of the travel time. 

> The radar sensors have the potential to be more useful than the Bluetooth sensors because it could not only detect pedestrians, cyclists, and cars without active Bluetooth devices, but could also measure their speed.

**Comment by mateoclarke** [comment]
got the slides from Itamar...
[CTR_OpenAustin_081516.pdf](https://github.com/open-austin/iced-coffee/files/434090/CTR_OpenAustin_081516.pdf)

**Comment by mateoclarke** [comment]
https://www.open-austin.org/blog/2016/09/12/aug-meetup-recap
