### ISSUE TITLE
WWOD Blog post

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#196]
I need to update the blog with the presentations from this past weekend

Need to finish wrangling presentations
- [ ] No SQL vs SQL presentation
- [ ] Data.world Preesentation
- [x] City resources 
- [x] Mapping

**Comment by mateoclarke** [comment]
I think too much time has passed since this event for a meaningful blog post. But looking at this, made me think of something... 

I had a conversation today with an Open Austin participant who recommended we start using Medium bc it is easier to draft and collaborate than via Jekyll. Wonder if you have thoughts about that @VictoriaODell.

We could still export the final from Medium to Jekyll so we have some control if we abandon Medium one day.
