### ISSUE TITLE
February Newsletter

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#214]
We have two recent blog posts we can highlight:
- https://www.open-austin.org/blog/2017/02/08/budget-party-mozilla-gigabit-grant-announcement
- https://www.open-austin.org/blog/2017/01/17/yearly-review

We have a bunch of upcoming hack nights we can highlight...

We have ATX Floods Fellowship Team speaking we can preview.

We have Open Data Day/Hack the Traffic event on March 4th

We can send a link to the Leadership Team application.

@VictoriaODell @mapineda What help do y'all need to get the Newsletter train rolling again?

**Comment by VictoriaODell** [comment]
Hey, we can aim for this Tuesday since that would be back on Schedule. 
We need list updated probably. 

I started working on the draft based on what you put here but will have more time to work on it tomorrows: [link to newsletter planning doc](https://docs.google.com/document/d/1E1QGjLEWObfBsTN6IXt1eNu6Dggmm_4W6emLbhllAFQ/edit)

**Comment by mapineda** [comment]
I'll update the list tomorrow 

Marco Pineda

**Comment by VictoriaODell** [comment]
Formatted in Google Drive and Campaign set up. I'll transfer over to MailChimp in the am, test, and send. 😴

**Comment by VictoriaODell** [comment]
Sent earlier today!

**Comment by mateoclarke** [comment]
Yay! ❤️
