### ISSUE TITLE
Hackpad is shutting down

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#251]
<img width="551" alt="screen shot 2017-04-26 at 6 43 01 pm" src="https://cloud.githubusercontent.com/assets/5697474/25512684/310a1362-2b95-11e7-94e0-b56987fbecd5.png">

I'm going to download [our hackpads](https://openaustin.hackpad.com/) as Markdown and upload them to a new github repo for archival sake using this chrome extension.
https://chrome.google.com/webstore/detail/hackpad-downloader/jhkfiecgggifjcoliemlcajokapmcpih/related?hl=en

What should we use at hacknights going forward? Paper? @seandellis, you're a paper fan right? 

Google Docs might be a good option bc ppl are very used to collaborating with it?

**Comment by mateoclarke** [comment]
https://github.com/open-austin/hackpad

**Comment by seandellis** [comment]
@mateoclarke I'd say it depends on their intended use.

Paper is nice because it offers the ease of editing a doc, but can be viewed as a presentation. The annoying thing is that it's an additional tool to use. 🙁

If they're single use presentations and for ease of use, Google Slides might be our best bet.

**Comment by mateoclarke** [comment]
Been using Paper at the last two Hack Nights. Seems to work well enough. Closing this issue...
