### ISSUE TITLE
Update + Evangelize Sign in 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#259]
@seandellis and I have decided to separate sign-in from membership. 
From now on our sign-up sheet will only have first/last name + email. So, for now, we just need to simplify sign in. 

Membership is another process we are working on in issue #257 

We want to capture actual numbers of attendees so we can have a better idea for planning and sponsorships. Sign up will be essentially required for those that choose to be affiliated members.

**Comment by VictoriaODell** [comment]
@seandellis something I didn't think about but when we simplify sign in will we have to ask for their shirt size every time if that's information we want to capture? I don't think it's a huge deal just feels a little silly now that I think about it.

**Comment by seandellis** [comment]
@VictoriaODell  True it does seem silly, but I think it might help incentivize sign in. I've added it as an optional question.

You can now see their shirt size and verify that they've signed in on our membership spreadsheet.

**Comment by VictoriaODell** [comment]
@seandellis this isn't something that we initially discussed but I want to bring it up here since It's relevant. 

What are your thoughts on adding a question about what district members are in? I got the idea while at the OGP workshops while talking to Kerry. I think if we have an idea of what districts members are in then we can get a better idea of how we can mobilize people on the policy side. It would also give us an idea of what representation looks like inside of Open Austin. 

Interested to hear if @mscarey has any thoughts on this as Policy lead.

**Comment by seandellis** [comment]
@VictoriaODell That certainly seems doable as an optional field.

Would that be for people applying for membership or for attendees? 

I'm concerned, since it's a hurdle because most people don't know what district they are in. Including myself. 😥 I tried to find mine by searching.

The city's site only shows a white box instead of the districting map. 😡

https://www.austintexas.gov/page/10-one-districting-map

The Vote Travis site isn't using https so I'm not comfortable plugging in my birthdate. 😠

http://www.votetravis.com/vexpress/display.do

Are there any other sites we could direct users to look it up? Are they mobile friendly?

pinging @mateoclarke @mscarey in case either of you know of any other sites.

**Comment by mateoclarke** [comment]
http://www.austintexas.gov/government (also not https)
http://myreps.datamade.us/ (also not https)

**Comment by mateoclarke** [comment]
I think this is the map that doesn't current load as an embed on the `https://www.austintexas.gov/page/10-one-districting-map` page: 
http://www.austintexas.gov/GIS/CouncilDistrictMap/

**Comment by mateoclarke** [comment]
Either way, I'm going to hack on something because I've heard a lot of people complain about this.

**Comment by seandellis** [comment]
@mateoclarke For our needs, I think [My Reps](http://myreps.datamade.us) will work best since it offers a simple address lookup. For those concerned with privacy they could look up an address in their neighborhood.

I was mainly annoyed with Vote Travis due to the lack of HTTPS since it asks for birth date.

**Comment by VictoriaODell** [comment]
My Reps looks great for our purposed right now. It's also open source~

Re: Who we ask this questions to: I think it's a must for members. Maybe optional for attendees? I'm open to have a discussion on that. Maybe we should do some additional work to inform people about districts or have someone who has expertise in that come in for a presentation. I was unaware of my district until OA people started chattering about it and that prompted me to look mine up. 

Also, I'm interested to chat with @mscarey about strategy around policy. I think we can make a more informed decision on when + where to ask.

**Comment by mscarey** [comment]
Sounds like a good thing to ask. Could be a good way to target people for
district-specific projects. Can members have a profile where questions like
this could go, to fill out once and update only when needed? "None" or
"Outside Austin" should be a valid response too.

On Aug 4, 2017 11:25 AM, "VictoriaODell" <notifications@github.com> wrote:

My Reps looks great for our purposed right now. It's also open source~

Re: Who we ask this questions to: I think it's a must for members. Maybe
optional for attendees? I'm open to have a discussion on that. Maybe we
should do some additional work to inform people about districts or have
someone who has expertise in that come in for a presentation. I was unaware
of my district until OA people started chattering about it and that
prompted me to look mine up.

Also, I'm interested to chat with @mscarey <https://github.com/mscarey>
about strategy around policy. I think we can make a more informed decision
on when + where to ask.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/open-austin/iced-coffee/issues/259#issuecomment-320320497>,
or mute the thread

**Comment by seandellis** [comment]
I've added the "What is your district" as an optional question to the standard sign in form.

Live form here: https://docs.google.com/forms/d/e/1FAIpQLSd799C8EF7cCXmuSM9jfYPFSlPGPReFOao_GTaI58QD_w5FPg/viewform
