### ISSUE TITLE
Schedule of Events 2020

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#373]
_this continues an old pattern of how we listed our events from 2018 and before, see #287_ 

Our proposed general pattern (with exceptions for holidays) is:
- Community Action Night #1 (1st Monday)
- Leadership Call once a month (2nd Monday)
- Community Action Night #2 (3rd Wednesday)
- ATA speaker series events (1st Tuesday or 4th Wednesday)

### January
- [ ] Thursday 1/9 - [Census Design Jam](https://www.meetup.com/Austin-Design-Jam/events/267325373/) -  Venue: General Assembly
- [ ] Wed 1/15 - Community Action Night - **Venue: TBD**
- _Mon, January 20 - MLK Holiday_ 
- [ ] Sunday 1/20 - IRL OA Leadership 2020 Kickoff - Venue: Mateo's house or Central Library
- [ ] Week of 1/27 select Census Workshop 
- _No ATA speaker series in Jan_

### February 
- **TBD** ATA speaker series event - date/time - venue
- [ ] TODO

### March
- [ ] TODO

### April
- [ ] TODO

### May
- [ ] TODO

### June
- [ ] TODO

### July
- [ ] TODO

### August
- [ ] TODO

### September
- [ ] TODO

### October
- [ ] TODO

### November
- [ ] TODO

### December
- [ ] TODO

**Comment by lianilychee** [comment]
"Couple" of questions.

**CANs:**
Is it possible to have the CANs on the same day for consistency?  Is there a reason the CANs are on different days?  Is it to accommodate people who have a recurring commitment on, for example, Tuesdays, and wouldn't be able to make any Tuesday CANs?  (Just picking Tuesdays)  I know Mateo you have specifically mentioned this challenge personally, and I don't want this to come off as dismissive because I think your presence is critical because you bring so much to CANs, but I wonder if (a) there is a way we can determine how extensive of a challenge this is for the broader membership and/or (b) we can draw on other brigades' experiences via CfA Slack.  I would very much value consistency from a personal perspective and a project/expectation management perspective, but the former leaves us with two data points and the latter is an intuition based on brief experience and Brigade Congress convos.

**ATA speaker series**
again re: consistency -- Is this floating between the first week and the last week because that is how ATA's schedule works?

**Comment by mateoclarke** [comment]
**CAN**: I'm open to having both monthly CANs on the same days of the month. I have an almost weekly commitment on Tuesdays, and I know other people have other weekly commitments like evening classes, so the idea on doing a M/W or T/W staggered schedule was to accommodate people. But let's go with consistency and adjust from there if needed. It certainly is more simple. 
**ATA**: I think January was just weird for scheduling for ATA. @smarrison could elaborate on that.
