### ISSUE TITLE
Open Austin Infographic

### ISSUE THREAD

**Issue by amaliebarras** [open-austin/iced-coffee#43]
Create assets using membership data to help future fundraising efforts

**Comment by amaliebarras** [comment]
#format
pdf

#data points
##events
number of hackathons
number of hack nights
number of tacos purchased
number of speakers

##projects
projects and their stages
categories of projects
number of commits on github

##people
number of users who've committed
data from membership slide
social media


##admin
1 new website
1 new logo
3 new core team members

**Comment by amaliebarras** [comment]
[OAInfographicV1.pdf](https://github.com/open-austin/iced-coffee/files/85346/OAInfographicV1.pdf)

First version! I just used the data that was readily available. Couldn't find some of the points like speakers and tacos, but I replaced with stuff I knew we did have. Do y'all have any...

- questions about or corrections to the data?
- additional data points? 
- design feedback? 
- suggestions for something to put at the end so it doesn't feel abrupt?

**Comment by mateoclarke** [comment]
This is great! 

Would recommend these changes:
- under events: name of the hackathon instead of venue. also include MyCreekATX maybe?
- very hard to read the skills listed. also the colors don't seem to fit the rest of the scheme.
- wondering what the "10 hacked on means", are those projects within the open austin repo? that's one thing that we need to try to figure out is keeping a list of projects/repos that aren't under our official repo. There might be a handful of OA member projects under individual's accounts.
- also wondering if commits or pull requests would be a bigger/more impressive metric from github.
- people stats is great, super impressive!

**Comment by amaliebarras** [comment]
Thanks for the feedback! 

- Agree on changing to hackathon name instead
- Agree on the pie chart… I fought with it for so long and couldn’t get it right. think I’ll just change it to a bar instead. pie charts are dumb anyway
- 10 hacked on is something I took from our end-of-year wrap up presentation, the “alphas and experiments” and I took the 3 from “beta and official”, would you use those words instead?
- Totally agree that commits and PRs would be better metrics, how do I find those for our organization? would I just have to add up in each project manually? 
- sweet! we had a lot of positive momentum from having presence at hackathons, excited to watch us grow this year. I was so impressed with the turnout at the lightning talks meetup.

**Comment by mateoclarke** [comment]
Yeah, I can look into Github metrics for you. Maybe with @luqmaan's help. I know there is a way use the Github API to query data from an organization or from repos. 

For example, this url endpoint returns all the "[events](https://developer.github.com/v3/activity/events/types/)" that occur in our org's repos. The only thing tricky is that this includes comments and other more trivial events. Not sure the type name specific to commits.
https://api.github.com/orgs/open-austin/events

Or a better way might be to query each repo we care about for its commits like this example with instabus.
https://api.github.com/repos/open-austin/instabus/commits?since=2015-01-01T00:00:00Z&until=2016-01-01T00:00:00Z

For more info on the github API: https://developer.github.com/v3/git/commits/

**Comment by amaliebarras** [comment]
[OAInfographicv2.pdf](https://github.com/open-austin/iced-coffee/files/90852/OAInfographicv2.pdf)

Cool! Here are all the edits except the github metrics.

**Comment by mateoclarke** [comment]
@amaliebarras: I think this version is good to ship. We could add more fine grade github details but I think its more trouble than its worth and there is already enough content in this. And I don't want to hold you back. 

What are the next steps? How do should we push this out?

**Comment by amaliebarras** [comment]
I can PDF it and put it in the Google Drive in the Photos & Design Files folder. 

Up to y'all as far as what we use it for. There was another issue on there that linked to it I'm pretty sure. I think one of the ideas was to use it to help with sponsorship too. @VictoriaODell Did you have anything in mind for using this on social, etc?

**Comment by amaliebarras** [comment]
[OAInfographicV3.pdf](https://github.com/open-austin/iced-coffee/files/95094/OAInfographicV3.pdf)

Changed it to say 2015 instead of 2016 - lol.. and moved a couple pixels. It's in the drive now

**Comment by mateoclarke** [comment]
Let's plan to include this in the first blog post once the new site is live. #52 
We should tweet it out then too.
