### ISSUE TITLE
Speakers for OpenGovCivTech Meetups

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#46]
- [x] JAN 11: Lighting Talks
- [x] FEB 22: Designing for 100% of America - Ben Guhin
- [x] MAR 21: Police Body Cameras - Kathy Mitchell, Texas Electronic Privacy Coalition
- [x] APR 18: Austin's Atlas - Ann Armstrong (Joint Event with Maptime ATX)
- [x] MAY 16: State Water Plan Site Demo, James Seppi, TNRIS
- [x] JUNE 20: Lighting Talks!
  - Diego H  (Sass Colors) 
  - Paul Serraino (Leaflet + React examples)
  - Amalie Barras (PANDA aka Community Data Portal)
  - Nik Collins (Commute.ly)
  - Vickie O'Dell (Permitting App)
- [x] JULY 18: Participatory Budgeting, Grace Atkins, Glasshouse Policy
- [x] AUG 15: Transportation & Sensors, Jen Duthie, UT Center for Transportation Research
- [x] SEPT 19: Elections & Voting Lightning Talks
- [x] OCT 17: data.world, Jonathan Ortiz
- [x] NOV 14: Civic Tech in the Age of Trump & Defining our values workshop
- [ ] DEC 12: State of the Union

Ideas:
- somebody from http://civicanalytics.com/
- somebody from community impact, statesman, or tribune working on data apps
- Kirk Goldsberry (http://kirkgoldsberry.com/) UT Adjunct
- ✅ Glasshouse Policy, Francisco Enriquez, Co-Founder and Managing Director
- ✅ Joint Open Austin/Maptime ATX/ ATXOSG
- short discussions/break out groups (what topics?)
- ✅ another round of Lightning Talks
- Andy Thorton on d3: http://encodingpixels.com/
- Cindy Royal from Texas State and Hack and Hackers
- Jon Lebkowsky from EFF Austin
- http://ctr.utexas.edu/nmc/people/jennifer-duthie/
- http://sevenmilemedia.com/work/
- Armand Chaput from UT about applications for drones by City agencies. http://www.austinmonitor.com/stories/2016/04/austin-fire-department-soon-using-drones/ 
- "Hey how'd you get that!?" Journalists share secrets to a successful FOIA request (could be the same talk as Cindy Royal?)

**Comment by VictoriaODell** [comment]
I think we should also consider short discussions followed by break-out groups. 

I've done that previously within an organization(Feminists United) and it got a great response since everyone got presented to for a bit and then we went into smaller groups to further discuss the issues. In the end we came together and recapped a bit on what each group discussed in relation to the topic. 

We did this for issues such as racism, classism, privlege, etc. It helped people stay engaged and made us a tighter community. 

We did a few things in that group that I really liked and need to probably share. 
1. We quickly addressed 3 headlines that were related to our cause at the beginning of the session. It was always better if they coresponded with the topic but sometimes it was more about current events. 

2. We switched it up between breakout groups/ presentations hosted by core team members, curated guest panels, and presentations by outside individuals(We had PPTXV come talk about voting rights, etc ). Also though, these meetings were held weekly so we had a lot more topics to cover and ultimately planning to do. I was on a team of about 7 people.

3. At the end of the meeting we had anonymous paper feedback cards that asked what each person liked/ thinks needs adjustments. This helped us gauge how each meeting went and helped us in planning future meetings. 

4. As a feminist group we were very particular about the use of personal pronouns in intros. I'd like to see that in more spaces but would like to know what the group thinks. Being more cognizant of things like really shows respect for underrepresented and underserved communities. I've heard that the Sass group does that too. It's a really small thing that can make a big difference for people. 

I learned a lot with that group and in a semster we grew 3x our orignial size because of better marketing(new logos, social media curation/maintenance,etc ), meeting structure, and overall organization. Let me know what ya'll think about the above and if we can incoporate any of it moving forward. 

Let me know if y'all have any questions too. I can maybe dig around and find some old stuff that we used. I think that group took a lot more work since we met weekly but  there were 7 people on the team.

**Comment by mateoclarke** [comment]
https://www.glasshousepolicy.org/
Francisco Enriquez, Co-Founder and Managing Director

> In the 84th Legislative Session, Glasshouse Policy crowdsourced public opinion on Texas fire prevention policies. Working with advocates and stakeholders from across Texas, Glasshouse Policy produced a citizen-sourced, collaboratively produced set of policy recommendations informed directly by our crowdsourcing platform. In 2017, Glasshouse Policy will continue our Texas Capitol Project on a new set of state challenges.

**Comment by amaliebarras** [comment]
Cool, Becca A signed up for a lightning talk June 20!

**Comment by mateoclarke** [comment]
Yay, I'll add a list to the top.

**Comment by mateoclarke** [comment]
Started a new todo for 2017, closing this one.
