### ISSUE TITLE
Capitalize on the presidential election year 7/16

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/iced-coffee#66]
- [ ] Get VoteATX up and running with updated County Clerk data
- [ ] Aug/Sept, requesting polling locations
- [ ] Sept/Oct, cleaning data and adding to app
- [x] Update Policy Guide & Candidate Questionnaires
- [ ] June/July/Aug
  Invite Annette Strauss Institute rep to Open Gov & Civic Tech Meetup in late summer/early fall

**Comment by mateoclarke** [comment]
@avickers mentioned to me at ATX Hack for Change that he was interested in helping lead efforts for VoteATX. He helped with the front end last time around.

**Comment by mateoclarke** [comment]
Some thoughts on this as I close out this issue:

VoteATX when we first launched and promoted it was novel. We lead the way and now a bunch of other folks have found value in creating maps that not only show polling times, locations, but also how long the wait is. The team around VoteATX didn't crystallize this year because the need for this project is not longer as evident, at least in Travis County. 

We were able to include FOMO.vote and the Travis County Election Team at a hack night so they could spread the word about their resources.

The Candidate Questionnaire was very successful this year with participation from most serious candidates. The content was included in the [Austin Tech Alliance Mobile App](https://itunes.apple.com/us/app/austin-tech-alliance/id1164265992?mt=8)
