### ISSUE TITLE
Update projects list

### ISSUE THREAD

**Issue by luqmaan** [open-austin/iced-coffee#71]
We need to update the projects list that shows up at http://www.codeforamerica.org/brigade/projects?q=austin.

What projects are missing?

Some lists
- https://github.com/open-austin/ship-it-2015/blob/master/README.md
- https://gist.github.com/luqmaan/bd4df852c4c460c0c79e
- https://gist.github.com/mateoclarke/b0c4c0ce6f30f3a6aff8

**Comment by mateoclarke** [comment]
And this is currently our master list and what populates the data that gets sent to CfA right? 
https://github.com/open-austin/Civic_Project/tree/master/projects

Would it be easier to manually update a Google Spreadsheet? Or a csv hosted on Github? Instead of having all of these yml files updated separately and then running a rake task to create new documents? Or is this system sufficient? If so, what can we do to update it more frequently? One positive to `Civic_Project` is that is already set up to create what CfA consumes and what gets sent to http://www.open-austin.org/hack-team/projects

There should also be the discussion of how project stages fits into all of this, experiment, alpha, beta, official...

**Comment by mateoclarke** [comment]
CFA's project page is defunct. Closing this.
